epochs: 300
n_classes: 4
background_class_id: 0
input_res: [225, 300, 3] # Height, width, channels
batch_size: 32
l2_regularization: 0.0005
min_scale: 0.2
max_scale: 0.9
scales: null
aspect_ratios_global: null
aspect_ratios_per_layer: [
  [0.05, 0.5, 1.0],
  [0.05, 0.5, 0.75, 1.0, 1.3],
  [0.05, 0.5, 0.75, 1.0, 1.3],
  [0.05, 0.5, 0.75, 1.0, 1.3],
  [0.05, 0.5, 1.0],
  [0.05, 0.5, 1.0]
]
# aspect_ratios_per_layer: [[1.0, 2.0, 0.5], [1.0, 2.0, 0.5, 3.0, 1.0 / 3.0], [1.0, 2.0, 0.5, 3.0, 1.0 / 3.0],
                           #[1.0, 2.0, 0.5, 3.0, 1.0 / 3.0], [1.0, 2.0, 0.5], [1.0, 2.0, 0.5]]
two_boxes_for_ar1: True
steps: null
offsets: null
clip_boxes: False
variances: [1.0, 1.0, 1.0, 1.0]# The variances by which the encoded target coordinates are divided as in the original implementation
coords: 'centroids'
normalize_coords: True
subtract_mean: [123, 117, 104]
divide_by_stddev: null
swap_channels: [2, 1, 0] # SSD uses BGR images
confidence_thresh: 0.01
iou_threshold: 0.45
pos_iou_threshold: 0.5
top_k: 200
nms_max_output_size: 400
return_predictor_sizes: False
