<?xml version="1.0"?>

<robot name="ardrone" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find rotors_description)/urdf/component_snippets.xacro" />
  <!-- Instantiate ardrone "mechanics" -->
  <xacro:include filename="$(find rotors_description)/urdf/StableMax.xacro" />

  <!-- Instantiate a controller. -->
  <xacro:controller_plugin_macro namespace="${namespace}" imu_sub_topic="imu" />

  <xacro:if value="$(arg enable_mavlink_interface)">
    <!-- Instantiate mavlink telemetry interface. -->
    <xacro:default_mavlink_interface namespace="${namespace}" imu_sub_topic="imu" rotor_count="4" />
  </xacro:if>

  <!-- Mount an ADIS16448 IMU. -->
  <xacro:imu_plugin_macro
    namespace="${namespace}"
    imu_suffix=""
    parent_link="${namespace}/base_link"
    imu_topic="imu"
    mass_imu_sensor="0.03"
    gyroscope_noise_density="0.0003394"
    gyroscope_random_walk="0.000038785"
    gyroscope_bias_correlation_time="1000.0"
    gyroscope_turn_on_bias_sigma="0.0087"
    accelerometer_noise_density="0.004"
    accelerometer_random_walk="0.006"
    accelerometer_bias_correlation_time="300.0"
    accelerometer_turn_on_bias_sigma="0.1960">
    <inertia ixx="0.000001" ixy="0.0" ixz="0.0" iyy="0.000001" iyz="0.0" izz="0.000001" />
    <origin xyz="0.0 0 0.03" rpy="0 0 0" />
  </xacro:imu_plugin_macro>

  <xacro:camera_macro
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    camera_suffix="mono"
    frame_rate="20.0"
    horizontal_fov="2"
    image_width="752"
    image_height="480"
    image_format="L8"
    min_distance="0.02"
    max_distance="50"
    noise_mean="0.0"
    noise_stddev="0.007"
    enable_visual="false">

      <box size="0.05 0.05 0.02" />
      <origin xyz="${arm_length} 0 ${-arm_length/2}" rpy="0 0 0" />
    </xacro:camera_macro>

  <xacro:if value="$(arg enable_ground_truth)">
    <xacro:ground_truth_imu_and_odometry namespace="${namespace}" parent_link="${namespace}/base_link" />
  </xacro:if>

  <xacro:if value="$(arg enable_logging)">
    <!-- Instantiate a logger -->
    <xacro:bag_plugin_macro
      namespace="${namespace}"
      bag_file="$(arg log_file)"
      rotor_velocity_slowdown_sim="${rotor_velocity_slowdown_sim}"
      wait_to_record_bag="$(arg wait_to_record_bag)" />
  </xacro:if>

</robot>
